### ISSUE TITLE
Missing Breakdance

### ISSUE THREAD

**Issue by igorchook** [f3l1x98/blish-emotes#75]
Hi hi! 👋
The /Breakdance emote seems to be missing 🥲.

**Comment by f3l1x98** [comment]
Oh I seem to have overlooked it due to it missing from the list in the API specs.
Will add it asap, thanks 👍

**Comment by f3l1x98** [comment]
Added in #77.
Just waiting for the release to be accepted.

**Comment by igorchook** [comment]
It's there, woot!!  Thanks a bunch! 🤗🥳
